In [ ]:
# Task 1:
#Load data as a data frame display first five and last five entities.
import pandas as pd
import numpy as np


data_array = pd.read_excel('Final Evaluation.xlsx')


dataframe = pd.DataFrame(data_array)


print('using iloc')
row0 = dataframe.iloc[0:4]
#row0
row1 = dataframe.iloc[-5:]
row1

In [ ]:
# Task 2:
#Load all spread sheets in different dataframe and combine all of them in a single
data_csv = pd.read_csv('Automobile_data.csv')
data_xlsx = pd.read_excel('Final Evaluation.xlsx')

data = pd.concat((data_xlsx,data_csv,),axis=0 )
data.to_excel('combined.xlsx' , index = True)

data

In [ ]:
# Task 3:
#Mark zero in place of missing data.

data_xlsx = pd.read_excel('Final Evaluation.xlsx')
data_xlsx
df_filled = data_xlsx.fillna(0)
df_filled

In [24]:
# #TASK 4
#Mark fail to those students who got less than 50 marks
import pandas as pd


df=pd.read_excel('Final Evaluation.xlsx')
df['Result'] = 'Nill'


df.iloc[:, 20] = pd.to_numeric(df.iloc[:, 20], errors='coerce')

df.loc[df.iloc[:, 20] <= 50, 'Result'] = 'Pass'
df.loc[df.iloc[:, 20] < 40, 'Result'] = 'Fail'

df

C:\Users\Barcha\AppData\Local\Temp\ipykernel_7500\85653126.py:10: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.iloc[:, 20] = pd.to_numeric(df.iloc[:, 20], errors='coerce')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Result
0,NaN,ASSIGNMENTS EVALUATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nill
1,NaN,Sr. No.,Roll No.,Name of Student,2022-08-03 00:00:00,2022-09-03 00:00:00,2022-10-03 00:00:00,14/3/2022,15/3/2022,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nill
2,NaN,1,AI21-C1-01,Rabiya Mubeen,10,10,10,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,Pass
3,NaN,2,AI21-C1-02,Sehrish Nazir,10,10,8,10,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,Pass
4,NaN,3,AI21-C1-03,Areeba Amin,0,NaN,2,NaN,6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,Fail
5,NaN,4,AI21-C1-04,Khadija Amin,10,10,10,10,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,Pass
6,NaN,5,AI21-C1-05,Sadia Irshad,0,0,NaN,4,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,Fail
7,NaN,6,AI21-C1-06,Amna Naveed,10,10,10,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,Pass
8,NaN,7,AI21-C1-07,Hamna Shaheen,10,10,10,10,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,Pass
9,NaN,8,AI21-C1-08,Alsyeda Uswah Mustafa,10,0,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,Fail
10,NaN,9,AI21-C1-09,Warda Mahboob,10,10,10,7,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,Pass
11,NaN,10,AI21-C1-10,Asra Imran,0,10,10,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,Fail
12,NaN,11,AI21-C1-11,Muhammad Qasim,0,10,10,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,Pass
13,NaN,12,AI21-C1-12,Muhammad Saqlain Arshad,10,NaN,0,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,Fail
14,NaN,13,AI21-C1-13,Khalid Mahmood,10,10,10,10,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,Pass
15,NaN,14,AI21-C1-14,Basir Riaz Toor,10,10,10,10,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,Pass
16,NaN,15,AI21-C1-15,Umer Arshad,10,10,10,0,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,Fail
17,NaN,16,AI21-C1-16,Ali Raza Shah,0,0,8,0,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,Fail
18,NaN,17,AI21-C1-17,Abdul Raouf,0,NaN,5,0,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,Fail
19,NaN,18,AI21-C1-18,Athar Ghuftar,10,10,0,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,Pass
20,NaN,19,AI21-C1-19,Muhammad Uzair Khan,0,0,9,0,6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,Fail
21,NaN,20,AI21-C1-20,Muhammad Ibtisam Ahmad,10,10,10,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,Pass
22,NaN,21,AI21-C1-21,Muhammad Ateeq Ur Rehman,10,0,0,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,Fail
23,NaN,22,AI21-C1-22,Muhammad Raahim Jamil,10,10,10,10,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,Pass
24,NaN,23,AI21-C1-23,Ch. Bilal Ur Rehman Sandhu,10,10,10,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,Pass
25,NaN,24,AI21-C1-24,Abdul Ahad Shahzad,10,10,10,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,Pass
26,NaN,25,AI21-C1-25,Yasir Ali,0,0,10,10,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,Fail
27,NaN,26,AI21-C2-01,Samia Tanveer,0,NaN,9,2,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,Fail
28,NaN,27,AI21-C2-02,Taqdees Komal,0,NaN,8,8,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,Fail
29,NaN,28,AI21-C2-03,Syeda Ghazia Shujat,10,10,10,7,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,Pass
30,NaN,29,AI21-C2-04,Arshia Naeem,0,0,10,7,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,Fail
31,NaN,30,AI21-C2-05,Bushra Mahin,10,10,10,10,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,Pass
32,NaN,31,AI21-C2-06,Asma Shehzadi,8,10,10,0,6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.0,Fail
33,NaN,32,AI21-C2-07,Farah Jabeen,0,0,2,10,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,Fail
34,NaN,33,AI21-C2-08,Amna Imran,0,k,7,0,6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,Fail
35,NaN,34,AI21-C2-09,Rimsha Kousar,3,0,NaN,d,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Fail
36,NaN,35,AI21-C2-10,Amina Tufail,0,0,10,0,cf,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,Fail
37,NaN,36,AI21-C2-11,Abdul Baseer,10,0,0,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,Fail
38,NaN,37,AI21-C2-12,Zeeshan Sharif,0,NaN,10,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,Fail
39,NaN,38,AI21-C2-13,Muhammad Ibraheem,10,10,0,3,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.0,Fail
40,NaN,39,AI21-C2-14,Khurram Iqbal,0,10,NaN,0,6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,Fail
41,NaN,40,AI21-C2-15,Muhammad Uzair,0,10,10,bkj,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,Fail
42,NaN,41,AI21-C2-16,Muhammad Awais Mutahir Qadri,10,10,0,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,Pass
43,NaN,42,AI21-C2-17,Muhammad Suleman Yameen,10,0,10,0,sgrf,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,Fail
44,NaN,43,AI21-C2-18,Waqas Sarwar,10,10,8,b,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,Fail
45,NaN,44,AI21-C2-19,M Harris Iqbal,10,8,0,10,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,Fail
46,NaN,45,AI21-C2-20,Noor Ul Amin Rao,0,10,8,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,Fail
47,NaN,46,AI21-C2-21,Mahr Maaz Bashir,10,10,10,10,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,Pass
48,NaN,47,AI21-C2-22,Huzaifa Tariq Butt,10,0,10,0,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,Fail
49,NaN,48,AI21-C2-23,Mukarram Munir,0,10,NaN,10,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,Fail
50,NaN,49,AI21-C2-24,Shahadat Ali,0,NaN,4,10,a,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,Fail
51,NaN,50,AI21-C2-25,Mohammad Awais,10,10,10,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,Pass
52,NaN,NaN,NaN,NaN,1,288,338,298,298,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,Nill

In [64]:
#Task 5:
#Make a new column as “GRADE” and assign grade according to this manner
import pandas as pd


df=pd.read_excel('Final Evaluation.xlsx')
df.iloc[:, 20] = pd.to_numeric(df.iloc[:, 20], errors='coerce')
df['Grade'] = 'Nill'
df
df.loc[df.iloc[:, 20] <= 50, 'Grade'] = 'A+'
df.loc[df.iloc[:, 20] < 45, 'Grade'] = 'A'
df.loc[df.iloc[:, 20] < 40, 'Grade'] = 'B'
df.loc[df.iloc[:, 20] < 30, 'Grade'] = 'C'
df.loc[df.iloc[:, 20] < 20, 'Grade'] = 'D'
df

C:\Users\Barcha\AppData\Local\Temp\ipykernel_7500\203069861.py:7: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.iloc[:, 20] = pd.to_numeric(df.iloc[:, 20], errors='coerce')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Grade
0,NaN,ASSIGNMENTS EVALUATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nill
1,NaN,Sr. No.,Roll No.,Name of Student,2022-08-03 00:00:00,2022-09-03 00:00:00,2022-10-03 00:00:00,14/3/2022,15/3/2022,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nill
2,NaN,1,AI21-C1-01,Rabiya Mubeen,10,10,10,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,A+
3,NaN,2,AI21-C1-02,Sehrish Nazir,10,10,8,10,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,A+
4,NaN,3,AI21-C1-03,Areeba Amin,0,NaN,2,NaN,6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,D
5,NaN,4,AI21-C1-04,Khadija Amin,10,10,10,10,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,A+
6,NaN,5,AI21-C1-05,Sadia Irshad,0,0,NaN,4,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,D
7,NaN,6,AI21-C1-06,Amna Naveed,10,10,10,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,A+
8,NaN,7,AI21-C1-07,Hamna Shaheen,10,10,10,10,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,A+
9,NaN,8,AI21-C1-08,Alsyeda Uswah Mustafa,10,0,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,D
10,NaN,9,AI21-C1-09,Warda Mahboob,10,10,10,7,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,A+
11,NaN,10,AI21-C1-10,Asra Imran,0,10,10,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,C
12,NaN,11,AI21-C1-11,Muhammad Qasim,0,10,10,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,A
13,NaN,12,AI21-C1-12,Muhammad Saqlain Arshad,10,NaN,0,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,B
14,NaN,13,AI21-C1-13,Khalid Mahmood,10,10,10,10,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,A
15,NaN,14,AI21-C1-14,Basir Riaz Toor,10,10,10,10,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,A+
16,NaN,15,AI21-C1-15,Umer Arshad,10,10,10,0,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,B
17,NaN,16,AI21-C1-16,Ali Raza Shah,0,0,8,0,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,D
18,NaN,17,AI21-C1-17,Abdul Raouf,0,NaN,5,0,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,D
19,NaN,18,AI21-C1-18,Athar Ghuftar,10,10,0,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,A
20,NaN,19,AI21-C1-19,Muhammad Uzair Khan,0,0,9,0,6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,D
21,NaN,20,AI21-C1-20,Muhammad Ibtisam Ahmad,10,10,10,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,A+
22,NaN,21,AI21-C1-21,Muhammad Ateeq Ur Rehman,10,0,0,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,B
23,NaN,22,AI21-C1-22,Muhammad Raahim Jamil,10,10,10,10,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,A+
24,NaN,23,AI21-C1-23,Ch. Bilal Ur Rehman Sandhu,10,10,10,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,A+
25,NaN,24,AI21-C1-24,Abdul Ahad Shahzad,10,10,10,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,A+
26,NaN,25,AI21-C1-25,Yasir Ali,0,0,10,10,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,C
27,NaN,26,AI21-C2-01,Samia Tanveer,0,NaN,9,2,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,D
28,NaN,27,AI21-C2-02,Taqdees Komal,0,NaN,8,8,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,D
29,NaN,28,AI21-C2-03,Syeda Ghazia Shujat,10,10,10,7,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,A+
30,NaN,29,AI21-C2-04,Arshia Naeem,0,0,10,7,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,C
31,NaN,30,AI21-C2-05,Bushra Mahin,10,10,10,10,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,A+
32,NaN,31,AI21-C2-06,Asma Shehzadi,8,10,10,0,6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.0,B
33,NaN,32,AI21-C2-07,Farah Jabeen,0,0,2,10,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,D
34,NaN,33,AI21-C2-08,Amna Imran,0,k,7,0,6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,D
35,NaN,34,AI21-C2-09,Rimsha Kousar,3,0,NaN,d,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,D
36,NaN,35,AI21-C2-10,Amina Tufail,0,0,10,0,cf,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,D
37,NaN,36,AI21-C2-11,Abdul Baseer,10,0,0,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,B
38,NaN,37,AI21-C2-12,Zeeshan Sharif,0,NaN,10,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,D
39,NaN,38,AI21-C2-13,Muhammad Ibraheem,10,10,0,3,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.0,B
40,NaN,39,AI21-C2-14,Khurram Iqbal,0,10,NaN,0,6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,D
41,NaN,40,AI21-C2-15,Muhammad Uzair,0,10,10,bkj,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,C
42,NaN,41,AI21-C2-16,Muhammad Awais Mutahir Qadri,10,10,0,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,A
43,NaN,42,AI21-C2-17,Muhammad Suleman Yameen,10,0,10,0,sgrf,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,C
44,NaN,43,AI21-C2-18,Waqas Sarwar,10,10,8,b,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,B
45,NaN,44,AI21-C2-19,M Harris Iqbal,10,8,0,10,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,C
46,NaN,45,AI21-C2-20,Noor Ul Amin Rao,0,10,8,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,B
47,NaN,46,AI21-C2-21,Mahr Maaz Bashir,10,10,10,10,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,A+
48,NaN,47,AI21-C2-22,Huzaifa Tariq Butt,10,0,10,0,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,B
49,NaN,48,AI21-C2-23,Mukarram Munir,0,10,NaN,10,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,C
50,NaN,49,AI21-C2-24,Shahadat Ali,0,NaN,4,10,a,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,D
51,NaN,50,AI21-C2-25,Mohammad Awais,10,10,10,10,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,A+
52,NaN,NaN,NaN,NaN,1,288,338,298,298,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,Nill

In [65]:
#Task 6:
#Rank your data frame with respect to total marks.
import pandas as pd
import numpy as np

# Assuming you have a DataFrame called 'df' with column 20 to be ranked
print(df)
# Replace missing values with zeros
df.replace(['n.a', 'NaN', 'Nill'], 0, inplace=True)
df.fillna(0, inplace=True)

df  =df.sort_values(by = 'Unnamed: 20',ascending = False)
df.reset_index(drop=True, inplace=True)
df.to_excel('df_sorted.xlsx',index = False)
df

    Unnamed: 0              Unnamed: 1  Unnamed: 2  \
0          NaN  ASSIGNMENTS EVALUATION         NaN
1          NaN                 Sr. No.    Roll No.
2          NaN                       1  AI21-C1-01
3          NaN                       2  AI21-C1-02
4          NaN                       3  AI21-C1-03
5          NaN                       4  AI21-C1-04
6          NaN                       5  AI21-C1-05
7          NaN                       6  AI21-C1-06
8          NaN                       7  AI21-C1-07
9          NaN                       8  AI21-C1-08
10         NaN                       9  AI21-C1-09
11         NaN                      10  AI21-C1-10
12         NaN                      11  AI21-C1-11
13         NaN                      12  AI21-C1-12
14         NaN                      13  AI21-C1-13
15         NaN                      14  AI21-C1-14
16         NaN                      15  AI21-C1-15
17         NaN                      16  AI21-C1-16
18         NaN                      17  AI21-C1-17
19         NaN                      18  AI21-C1-18
20         NaN                      19  AI21-C1-19
21         NaN                      20  AI21-C1-20
22         NaN                      21  AI21-C1-21
23         NaN                      22  AI21-C1-22
24         NaN                      23  AI21-C1-23
25         NaN                      24  AI21-C1-24
26         NaN                      25  AI21-C1-25
27         NaN                      26  AI21-C2-01
28         NaN                      27  AI21-C2-02
29         NaN                      28  AI21-C2-03
30         NaN                      29  AI21-C2-04
31         NaN                      30  AI21-C2-05
32         NaN                      31  AI21-C2-06
33         NaN                      32  AI21-C2-07
34         NaN                      33  AI21-C2-08
35         NaN                      34  AI21-C2-09
36         NaN                      35  AI21-C2-10
37         NaN                      36  AI21-C2-11
38         NaN                      37  AI21-C2-12
39         NaN                      38  AI21-C2-13
40         NaN                      39  AI21-C2-14
41         NaN                      40  AI21-C2-15
42         NaN                      41  AI21-C2-16
43         NaN                      42  AI21-C2-17
44         NaN                      43  AI21-C2-18
45         NaN                      44  AI21-C2-19
46         NaN                      45  AI21-C2-20
47         NaN                      46  AI21-C2-21
48         NaN                      47  AI21-C2-22
49         NaN                      48  AI21-C2-23
50         NaN                      49  AI21-C2-24
51         NaN                      50  AI21-C2-25
52         NaN                     NaN         NaN

                      Unnamed: 3           Unnamed: 4           Unnamed: 5  \
0                            NaN                  NaN                  NaN
1                Name of Student  2022-08-03 00:00:00  2022-09-03 00:00:00
2                  Rabiya Mubeen                   10                   10
3                  Sehrish Nazir                   10                   10
4                   Areeba Amin                     0                  NaN
5                   Khadija Amin                   10                   10
6                   Sadia Irshad                    0                    0
7                   Amna Naveed                    10                   10
8                  Hamna Shaheen                   10                   10
9          Alsyeda Uswah Mustafa                   10                    0
10                 Warda Mahboob                   10                   10
11                    Asra Imran                    0                   10
12               Muhammad Qasim                     0                   10
13       Muhammad Saqlain Arshad                   10                  NaN
14                Khalid Mahmood                   10                   10
15               Basir Riaz Toor                   10                   10
16                   Umer Arshad                   10                   10
17                 Ali Raza Shah                    0                    0
18                   Abdul Raouf                    0                  NaN
19                 Athar Ghuftar                   10                   10
20           Muhammad Uzair Khan                    0                    0
21       Muhammad Ibtisam Ahmad                    10                   10
22      Muhammad Ateeq Ur Rehman                   10                    0
23         Muhammad Raahim Jamil                   10                   10
24    Ch. Bilal Ur Rehman Sandhu                   10                   10
25            Abdul Ahad Shahzad                   10                   10
26                     Yasir Ali                    0                    0
27                 Samia Tanveer                    0                  NaN
28                 Taqdees Komal                    0                  NaN
29           Syeda Ghazia Shujat                   10                   10
30                  Arshia Naeem                    0                    0
31                  Bushra Mahin                   10                   10
32                 Asma Shehzadi                    8                   10
33                  Farah Jabeen                    0                    0
34                    Amna Imran                    0                    k
35                 Rimsha Kousar                    3                    0
36                  Amina Tufail                    0                    0
37                  Abdul Baseer                   10                    0
38                Zeeshan Sharif                    0                  NaN
39             Muhammad Ibraheem                   10                   10
40                 Khurram Iqbal                    0                   10
41             Muhammad Uzair                       0                   10
42  Muhammad Awais Mutahir Qadri                   10                   10
43       Muhammad Suleman Yameen                   10                    0
44                  Waqas Sarwar                   10                   10
45                M Harris Iqbal                   10                    8
46             Noor Ul Amin Rao                     0                   10
47              Mahr Maaz Bashir                   10                   10
48            Huzaifa Tariq Butt                   10                    0
49                Mukarram Munir                    0                   10
50                  Shahadat Ali                    0                  NaN
51                Mohammad Awais                   10                   10
52                           NaN                    1                  288

             Unnamed: 6 Unnamed: 7 Unnamed: 8  Unnamed: 9  ...  Unnamed: 12  \
0                   NaN        NaN        NaN         NaN  ...          NaN
1   2022-10-03 00:00:00  14/3/2022  15/3/2022         NaN  ...          NaN
2                    10         10         10         NaN  ...          NaN
3                     8         10          8         NaN  ...          NaN
4                     2        NaN          6         NaN  ...          NaN
5                    10         10          8         NaN  ...          NaN
6                   NaN          4          0         NaN  ...          NaN
7                    10         10         10         NaN  ...          NaN
8                    10         10          8         NaN  ...          NaN
9                   NaN          0          0         NaN  ...          NaN
10                   10          7          8         NaN  ...          NaN
11                   10        NaN          0         NaN  ...          NaN
12                   10         10         10         NaN  ...          NaN
13                    0         10         10         NaN  ...          NaN
14                   10         10          0         NaN  ...          NaN
15                   10         10          8         NaN  ...          NaN
16                   10          0          8         NaN  ...          NaN
17                    8          0          8         NaN  ...          NaN
18                    5          0          5         NaN  ...          NaN
19                    0         10         10         NaN  ...          NaN
20                    9          0          6         NaN  ...          NaN
21                   10         10         10         NaN  ...          NaN
22                    0         10         10         NaN  ...          NaN
23                   10         10          8         NaN  ...          NaN
24                   10         10         10         NaN  ...          NaN
25                   10         10         10         NaN  ...          NaN
26                   10         10          8         NaN  ...          NaN
27                    9          2          0         NaN  ...          NaN
28                    8          8          3         NaN  ...          NaN
29                   10          7          8         NaN  ...          NaN
30                   10          7          4         NaN  ...          NaN
31                   10         10          8         NaN  ...          NaN
32                   10          0          6         NaN  ...          NaN
33                    2         10          2         NaN  ...          NaN
34                    7          0          6         NaN  ...          NaN
35                  NaN          d          0         NaN  ...          NaN
36                   10          0         cf         NaN  ...          NaN
37                    0         10         10         NaN  ...          NaN
38                   10          0          0         NaN  ...          NaN
39                    0          3          8         NaN  ...          NaN
40                  NaN          0          6         NaN  ...          NaN
41                   10        bkj          0         NaN  ...          NaN
42                    0         10         10         NaN  ...          NaN
43                   10          0       sgrf         NaN  ...          NaN
44                    8          b         10         NaN  ...          NaN
45                    0         10          0         NaN  ...          NaN
46                    8         10         10         NaN  ...          NaN
47                   10         10          8         NaN  ...          NaN
48                   10          0         10         NaN  ...          NaN
49                  NaN         10          0         NaN  ...          NaN
50                    4         10          a         NaN  ...          NaN
51                   10         10         10         NaN  ...          NaN
52                  338        298        298         0.0  ...          0.0

    Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17  \
0           NaN          NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN          NaN
2           NaN          NaN          NaN          NaN          NaN
3           NaN          NaN          NaN          NaN          NaN
4           NaN          NaN          NaN          NaN          NaN
5           NaN          NaN          NaN          NaN          NaN
6           NaN          NaN          NaN          NaN          NaN
7           NaN          NaN          NaN          NaN          NaN
8           NaN          NaN          NaN          NaN          NaN
9           NaN          NaN          NaN          NaN          NaN
10          NaN          NaN          NaN          NaN          NaN
11          NaN          NaN          NaN          NaN          NaN
12          NaN          NaN          NaN          NaN          NaN
13          NaN          NaN          NaN          NaN          NaN
14          NaN          NaN          NaN          NaN          NaN
15          NaN          NaN          NaN          NaN          NaN
16          NaN          NaN          NaN          NaN          NaN
17          NaN          NaN          NaN          NaN          NaN
18          NaN          NaN          NaN          NaN          NaN
19          NaN          NaN          NaN          NaN          NaN
20          NaN          NaN          NaN          NaN          NaN
21          NaN          NaN          NaN          NaN          NaN
22          NaN          NaN          NaN          NaN          NaN
23          NaN          NaN          NaN          NaN          NaN
24          NaN          NaN          NaN          NaN          NaN
25          NaN          NaN          NaN          NaN          NaN
26          NaN          NaN          NaN          NaN          NaN
27          NaN          NaN          NaN          NaN          NaN
28          NaN          NaN          NaN          NaN          NaN
29          NaN          NaN          NaN          NaN          NaN
30          NaN          NaN          NaN          NaN          NaN
31          NaN          NaN          NaN          NaN          NaN
32          NaN          NaN          NaN          NaN          NaN
33          NaN          NaN          NaN          NaN          NaN
34          NaN          NaN          NaN          NaN          NaN
35          NaN          NaN          NaN          NaN          NaN
36          NaN          NaN          NaN          NaN          NaN
37          NaN          NaN          NaN          NaN          NaN
38          NaN          NaN          NaN          NaN          NaN
39          NaN          NaN          NaN          NaN          NaN
40          NaN          NaN          NaN          NaN          NaN
41          NaN          NaN          NaN          NaN          NaN
42          NaN          NaN          NaN          NaN          NaN
43          NaN          NaN          NaN          NaN          NaN
44          NaN          NaN          NaN          NaN          NaN
45          NaN          NaN          NaN          NaN          NaN
46          NaN          NaN          NaN          NaN          NaN
47          NaN          NaN          NaN          NaN          NaN
48          NaN          NaN          NaN          NaN          NaN
49          NaN          NaN          NaN          NaN          NaN
50          NaN          NaN          NaN          NaN          NaN
51          NaN          NaN          NaN          NaN          NaN
52          0.0          0.0          0.0          0.0          0.0

    Unnamed: 18  Unnamed: 19  Unnamed: 20  Grade
0           NaN          NaN          NaN   Nill
1           NaN          NaN          NaN   Nill
2           NaN          NaN         50.0     A+
3           NaN          NaN         46.0     A+
4           NaN          NaN          8.0      D
5           NaN          NaN         48.0     A+
6           NaN          NaN          4.0      D
7           NaN          NaN         50.0     A+
8           NaN          NaN         48.0     A+
9           NaN          NaN         10.0      D
10          NaN          NaN         45.0     A+
11          NaN          NaN         20.0      C
12          NaN          NaN         40.0      A
13          NaN          NaN         30.0      B
14          NaN          NaN         40.0      A
15          NaN          NaN         48.0     A+
16          NaN          NaN         38.0      B
17          NaN          NaN         16.0      D
18          NaN          NaN         10.0      D
19          NaN          NaN         40.0      A
20          NaN          NaN         15.0      D
21          NaN          NaN         50.0     A+
22          NaN          NaN         30.0      B
23          NaN          NaN         48.0     A+
24          NaN          NaN         50.0     A+
25          NaN          NaN         50.0     A+
26          NaN          NaN         28.0      C
27          NaN          NaN         11.0      D
28          NaN          NaN         19.0      D
29          NaN          NaN         45.0     A+
30          NaN          NaN         21.0      C
31          NaN          NaN         48.0     A+
32          NaN          NaN         34.0      B
33          NaN          NaN         14.0      D
34          NaN          NaN         13.0      D
35          NaN          NaN          3.0      D
36          NaN          NaN         10.0      D
37          NaN          NaN         30.0      B
38          NaN          NaN         10.0      D
39          NaN          NaN         31.0      B
40          NaN          NaN         16.0      D
41          NaN          NaN         20.0      C
42          NaN          NaN         40.0      A
43          NaN          NaN         20.0      C
44          NaN          NaN         38.0      B
45          NaN          NaN         28.0      C
46          NaN          NaN         38.0      B
47          NaN          NaN         48.0     A+
48          NaN          NaN         30.0      B
49          NaN          NaN         20.0      C
50          NaN          NaN         14.0      D
51          NaN          NaN         50.0     A+
52          0.0          0.0          NaN   Nill

[53 rows x 22 columns]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Grade
0,0.0,24,AI21-C1-24,Abdul Ahad Shahzad,10,10,10,10,10,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,A+
1,0.0,1,AI21-C1-01,Rabiya Mubeen,10,10,10,10,10,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,A+
2,0.0,50,AI21-C2-25,Mohammad Awais,10,10,10,10,10,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,A+
3,0.0,23,AI21-C1-23,Ch. Bilal Ur Rehman Sandhu,10,10,10,10,10,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,A+
4,0.0,20,AI21-C1-20,Muhammad Ibtisam Ahmad,10,10,10,10,10,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,A+
5,0.0,6,AI21-C1-06,Amna Naveed,10,10,10,10,10,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,A+
6,0.0,14,AI21-C1-14,Basir Riaz Toor,10,10,10,10,8,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,48.0,A+
7,0.0,22,AI21-C1-22,Muhammad Raahim Jamil,10,10,10,10,8,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,48.0,A+
8,0.0,30,AI21-C2-05,Bushra Mahin,10,10,10,10,8,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,48.0,A+
9,0.0,4,AI21-C1-04,Khadija Amin,10,10,10,10,8,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,48.0,A+
10,0.0,46,AI21-C2-21,Mahr Maaz Bashir,10,10,10,10,8,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,48.0,A+
11,0.0,7,AI21-C1-07,Hamna Shaheen,10,10,10,10,8,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,48.0,A+
12,0.0,2,AI21-C1-02,Sehrish Nazir,10,10,8,10,8,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.0,A+
13,0.0,28,AI21-C2-03,Syeda Ghazia Shujat,10,10,10,7,8,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45.0,A+
14,0.0,9,AI21-C1-09,Warda Mahboob,10,10,10,7,8,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45.0,A+
15,0.0,18,AI21-C1-18,Athar Ghuftar,10,10,0,10,10,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0,A
16,0.0,41,AI21-C2-16,Muhammad Awais Mutahir Qadri,10,10,0,10,10,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0,A
17,0.0,13,AI21-C1-13,Khalid Mahmood,10,10,10,10,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0,A
18,0.0,11,AI21-C1-11,Muhammad Qasim,0,10,10,10,10,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0,A
19,0.0,43,AI21-C2-18,Waqas Sarwar,10,10,8,b,10,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38.0,B
20,0.0,15,AI21-C1-15,Umer Arshad,10,10,10,0,8,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38.0,B
21,0.0,45,AI21-C2-20,Noor Ul Amin Rao,0,10,8,10,10,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38.0,B
22,0.0,31,AI21-C2-06,Asma Shehzadi,8,10,10,0,6,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.0,B
23,0.0,38,AI21-C2-13,Muhammad Ibraheem,10,10,0,3,8,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31.0,B
24,0.0,12,AI21-C1-12,Muhammad Saqlain Arshad,10,0,0,10,10,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,B
25,0.0,21,AI21-C1-21,Muhammad Ateeq Ur Rehman,10,0,0,10,10,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,B
26,0.0,47,AI21-C2-22,Huzaifa Tariq Butt,10,0,10,0,10,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,B
27,0.0,36,AI21-C2-11,Abdul Baseer,10,0,0,10,10,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,B
28,0.0,44,AI21-C2-19,M Harris Iqbal,10,8,0,10,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.0,C
29,0.0,25,AI21-C1-25,Yasir Ali,0,0,10,10,8,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.0,C
30,0.0,29,AI21-C2-04,Arshia Naeem,0,0,10,7,4,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0,C
31,0.0,40,AI21-C2-15,Muhammad Uzair,0,10,10,bkj,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,C
32,0.0,10,AI21-C1-10,Asra Imran,0,10,10,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,C
33,0.0,42,AI21-C2-17,Muhammad Suleman Yameen,10,0,10,0,sgrf,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,C
34,0.0,48,AI21-C2-23,Mukarram Munir,0,10,0,10,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,C
35,0.0,27,AI21-C2-02,Taqdees Komal,0,0,8,8,3,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0,D
36,0.0,16,AI21-C1-16,Ali Raza Shah,0,0,8,0,8,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,D
37,0.0,39,AI21-C2-14,Khurram Iqbal,0,10,0,0,6,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,D
38,0.0,19,AI21-C1-19,Muhammad Uzair Khan,0,0,9,0,6,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,D
39,0.0,49,AI21-C2-24,Shahadat Ali,0,0,4,10,a,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,D
40,0.0,32,AI21-C2-07,Farah Jabeen,0,0,2,10,2,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,D
41,0.0,33,AI21-C2-08,Amna Imran,0,k,7,0,6,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,D
42,0.0,26,AI21-C2-01,Samia Tanveer,0,0,9,2,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,D
43,0.0,35,AI21-C2-10,Amina Tufail,0,0,10,0,cf,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,D
44,0.0,37,AI21-C2-12,Zeeshan Sharif,0,0,10,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,D
45,0.0,17,AI21-C1-17,Abdul Raouf,0,0,5,0,5,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,D
46,0.0,8,AI21-C1-08,Alsyeda Uswah Mustafa,10,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,D
47,0.0,3,AI21-C1-03,Areeba Amin,0,0,2,0,6,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,D
48,0.0,5,AI21-C1-05,Sadia Irshad,0,0,0,4,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,D
49,0.0,34,AI21-C2-09,Rimsha Kousar,3,0,0,d,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,D
50,0.0,ASSIGNMENTS EVALUATION,0,0,0,0,0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
51,0.0,Sr. No.,Roll No.,Name of Student,2022-08-03 00:00:00,2022-09-03 00:00:00,2022-10-03 00:00:00,14/3/2022,15/3/2022,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
52,0.0,0,0,0,1,288,338,298,298,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [68]:
#Task 7:
#Calculate the average of total marks
import pandas as pd
import numpy as np


df=pd.read_excel('df_sorted.xlsx')
df.fillna(0, inplace=True)
mean =df.iloc[:, 20].mean()
print('mean')
mean

mean

28.547169811320753

In [85]:
#Task 8:
#Display the name of first three position holders.
positionHolders = df.iloc[1:5,3]
print(positionHolders )

1    Name of Student
2      Rabiya Mubeen
3      Sehrish Nazir
4       Areeba Amin
Name: Unnamed: 3, dtype: object

In [87]:
#Task 9:
#Save your data in excel file as a single spreadsheet
df.to_excel('fileIMP.xlsx',index = False)

# 2nd task

In [9]:
# AutoMobile_Dataset
#Task 1: From the given dataset print the first and last five rows.

data_array = pd.read_csv('Automobile_data.csv')


dataframe = pd.DataFrame(data_array)
print(dataframe)

print('using iloc')
row0 = dataframe.iloc[0:4]
#row0
row1 = dataframe.iloc[-5:]
row1

    index      company   body-style  wheel-base  length engine-type  \
0       0  alfa-romero  convertible        88.6   168.8        dohc
1       1  alfa-romero  convertible        88.6   168.8        dohc
2       2  alfa-romero    hatchback        94.5   171.2        ohcv
3       3         audi        sedan        99.8   176.6         ohc
4       4         audi        sedan        99.4   176.6         ohc
..    ...          ...          ...         ...     ...         ...
56     81   volkswagen        sedan        97.3   171.7         ohc
57     82   volkswagen        sedan        97.3   171.7         ohc
58     86   volkswagen        sedan        97.3   171.7         ohc
59     87        volvo        sedan       104.3   188.8         ohc
60     88        volvo        wagon       104.3   188.8         ohc

   num-of-cylinders  horsepower  average-mileage  price
0              four         111               21  13495
1              four         111               21  16500
2               six         154               19  16500
3              four         102               24  13950
4              five         115               18    n.a
..              ...         ...              ...    ...
56             four          85               27   7975
57             four          52               37   7995
58             four         100               26   9995
59             four         114               23  12940
60             four         114               23  13415

[61 rows x 10 columns]
using iloc

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415

In [16]:
# task 2
# Replace all column values which contain ?, n.a, or NaN.
data_array = pd.read_csv('Automobile_data.csv')


dataframe = pd.DataFrame(data_array)

dataframe.replace(['n.a', 'NaN'], 1, inplace=True)

dataframe

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,1
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415

In [18]:
# Task 3: Print most expensive car’s company name and price.

import pandas as pd

file= pd.read_csv("Automobile_data.csv", na_values=["n.a"])


max_price= file.loc[file["price"].idxmax()]


car_company = max_price["company"]
car_price = max_price["price"]

print("Company:", car_company)
print("Price:", car_price)

Company: mercedes-benz
Price: 45400.0

In [12]:
# Task 4: Count total cars per company
import pandas as pd
file= pd.read_csv("Automobile_data.csv", na_values=["n.a"])
file = file['company'].value_counts()
print('company      Cars')
print(file)

company      Cars
toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: company, dtype: int64

In [20]:
#Task 5: Find each company’s Highest price car
max_price = file.groupby('company')['price'].max().reset_index()
for index, row in max_price.iterrows():
    comp = row['company']
    maxprc = row['price']
    print("Company: " , comp)
    print("Highest: " , maxprc)

Company:  alfa-romero
Highest:  16500.0
Company:  audi
Highest:  18920.0
Company:  bmw
Highest:  41315.0
Company:  chevrolet
Highest:  6295.0
Company:  dodge
Highest:  6377.0
Company:  honda
Highest:  12945.0
Company:  isuzu
Highest:  6785.0
Company:  jaguar
Highest:  36000.0
Company:  mazda
Highest:  18344.0
Company:  mercedes-benz
Highest:  45400.0
Company:  mitsubishi
Highest:  8189.0
Company:  nissan
Highest:  13499.0
Company:  porsche
Highest:  37028.0
Company:  toyota
Highest:  15750.0
Company:  volkswagen
Highest:  9995.0
Company:  volvo
Highest:  13415.0

In [21]:
# Task 6: Find the average mileage of each car making company
import pandas as pd
average = file.groupby('company')['average-mileage'].mean().reset_index()
for index, row in average.iterrows():
    comp = row['company']
    maxprc = row['average-mileage']
    print("Company: " , comp)
    print("Average mileage: " , average)

Company:  alfa-romero
Average mileage:            company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000
Company:  audi
Average mileage:            company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000
Company:  bmw
Average mileage:            company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000
Company:  chevrolet
Average mileage:            company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000
Company:  dodge
Average mileage:            company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000
Company:  honda
Average mileage:            company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000
Company:  isuzu
Average mileage:            company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000
Company:  jaguar
Average mileage:            company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000
Company:  mazda
Average mileage:            company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000
Company:  mercedes-benz
Average mileage:            company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000
Company:  mitsubishi
Average mileage:            company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000
Company:  nissan
Average mileage:            company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000
Company:  porsche
Average mileage:            company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000
Company:  toyota
Average mileage:            company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000
Company:  volkswagen
Average mileage:            company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000
Company:  volvo
Average mileage:            company  average-mileage
0     alfa-romero        20.333333
1            audi        20.000000
2             bmw        19.000000
3       chevrolet        41.000000
4           dodge        31.000000
5           honda        26.333333
6           isuzu        33.333333
7          jaguar        14.333333
8           mazda        28.000000
9   mercedes-benz        18.000000
10     mitsubishi        29.500000
11         nissan        31.400000
12        porsche        17.000000
13         toyota        28.714286
14     volkswagen        31.750000
15          volvo        23.000000

In [14]:
#Task 7: Sort all cars by Price column

import pandas as pd

file= pd.read_csv("Automobile_data.csv", na_values=["n.a"])
averag = file.sort_values('price' ,ascending = False)
averag

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
35,47,mercedes-benz,hardtop,112.0,199.2,ohcv,eight,184,14,45400.0
11,14,bmw,sedan,103.5,193.8,ohc,six,182,16,41315.0
34,46,mercedes-benz,sedan,120.9,208.1,ohcv,eight,184,14,40960.0
46,62,porsche,convertible,89.5,168.9,ohcf,six,207,17,37028.0
12,15,bmw,sedan,110.0,197.0,ohc,six,182,15,36880.0
...,...,...,...,...,...,...,...,...,...,...
15,18,chevrolet,sedan,94.5,158.8,ohc,four,70,38,NaN
20,29,honda,sedan,96.5,169.1,ohc,four,100,25,NaN
22,31,isuzu,sedan,94.5,155.9,ohc,four,70,38,NaN
23,32,isuzu,sedan,94.5,155.9,ohc,four,70,38,NaN
47,63,porsche,hatchback,98.4,175.7,dohcv,eight,288,17,NaN